#Create a Python program using at least 10 string methods from the table below and show their outputs with examples. Try methods like upper(), split(), replace(), find() and strip()
string_1=input("ENTER ANYTHING :\n")
print(string_1.upper())
print(string_1.lower())
print(string_1.find("a"))
print(string_1.replace("hi","NAMASTE"))
print(string_1.capitalize())
print(string_1.startswith("N"))
print(string_1.endswith("d"))
print(string_1.split(sep=" "))
print(string_1.strip())
print(string_1.find("h"))
print(string_1.isupper())
print(string_1.islower())